module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  safelist: [
    "bg-primary-1",
    "bg-primary-2",
    "bg-primary-3",
    "bg-primary-4",
    "bg-primary-5",
    "bg-primary-6",
    "bg-primary-7",
    "bg-primary-8",
    "bg-primary-9",
    "bg-primary-10",
  ],
  theme: {
    extend: {
      fontSize: {
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
      },
      colors: {
        white: "var(--white)",
        "white-2": "var(--white-2)",
        secondary: "var(--secondary)",
        grey: "var(--grey)",
        txt: "var(--txt)",
        "bg-main-bg-1": "var(--bg-main-bg-1)",
        "bg-card-bg-2": "var(--bg-card-bg-2)",
        "bg-card-bg-3": "var(--bg-card-bg-3)",
        "bg-extra": "var(--bg-extra)",
        "grey-1": "var(--grey-1)",
        "grey-2": "var(--grey-2)",
        "grey-3": "var(--grey-3)",
        "grey-4": "var(--grey-4)",
        "grey-5": "var(--grey-5)",
        "grey-paragraph-6": "var(--grey-paragraph-6)",
        "grey-7": "var(--grey-7)",
        "grey-paragraph-8": "var(--grey-paragraph-8)",
        "grey-9": "var(--grey-9)",
        "grey-10": "var(--grey-10)",
        "primary-1": "var(--primary-1)",
        "primary-2": "var(--primary-2)",
        "primary-3": "var(--primary-3)",
        "primary-4": "var(--primary-4)",
        "primary-5": "var(--primary-5)",
        "primary-6": "var(--primary-6)",
        "primary-7": "var(--primary-7)",
        "primary-8": "var(--primary-8)",
        "primary-9": "var(--primary-9)",
        "primary-10": "var(--primary-10)",
        "graph-success-main": "var(--graph-success-main)",
        "graph-success-light": "var(--graph-success-light)",
        "graph-error-main": "var(--graph-error-main)",
        "graph-error-light": "var(--graph-error-light)",
        "graph-warning-main": "var(--graph-warning-main)",
        "graph-warning-light": "var(--graph-warning-light)",
      },
    },
  },
  plugins: [],
};
